package com.hoang.jobfinder.common;

public interface ErrorCode {
  String SUCCESS = "SUCCESS";
  String VALIDATION_ERROR = "VALIDATION_ERROR";
  String UNAUTHORIZED = "UNAUTHORIZED";
  String FORBIDDEN = "FORBIDDEN";
  String NOT_FOUND = "NOT_FOUND";
  String INTERNAL_ERROR = "INTERNAL_ERROR";
  String BAD_REQUEST = "BAD_REQUEST";
  String INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
  String EXISTED_USER = "EXISTED_USER";
  String ILLEGAL_ARGUMENT = "ILLEGAL_ARGUMENT";
}
